language: php

services:
  - mongodb

php:
  - 5.3
  - 5.4

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongo admin --eval 'db.addUser("travis", "test");'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit --coverage-text