language: php

env:
  global:
    - PHPCS=0
    - RUN_TESTS=1

services:
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

matrix:
  include:
    - php: 5.6
      env: PHPCS=1 RUN_TESTS=0

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev -o

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then phpunit --coverage-text; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --extensions=php --standard=psr2 ./src; fi"
