language: php

services:
  - mongodb

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev -o
  - composer require 'phpunit/phpunit=3.7.*'

script: ./vendor/phpunit/phpunit/composer/bin/phpunit --coverage-text
