language: php

services:
  - mongodb

php:
  - 5.3
  - 5.4

before_script:
  - pecl install mongo-beta
  - mongo admin --eval 'db.addUser("travis", "test");'
  - composer install --dev

script: phpunit